= Openshift Spice Runner

The Ansible Runner project to deploy operators and their related Custom Resources to OpenShift. 

The role https://github.com/kameshsampath/ansible-role-openshift-spices[OpenShift Spices], allows install and configure the following software components using operators:

- [*] Red Hat OpenShift Serverless both Serving and Eventing

- [*] Red Hat OpenShift Pipelines

- [*] https://argoproj.github.io/argo-cd/[Argo CD]

- [*] Red Hat OpenShift Service Mesh

- [*] https://strimzi.io[Strimzi Kafka]

- [*] https://www.redhat.com/en/technologies/management/advanced-cluster-management[Red Hat Advanced Cluster Management for Kubernetes]

- [ ] https://skupper.io[Skupper]

- [*] https://camel.apache.org/docs/#camel-k[Apache Camel-K]

- [*] https://www.eclipse.org/che/[Eclipse Che]

== Pre-requisites

- Docker for Mac or Windows (OR) Docker/podman for Linux

== Clone sources

[source,bash,subs="marcos+,+attributes]
----
git clone https://github.com/openshift-spice-runner
export PROJECT_HOME=`pwd`/openshift-spice-runner
----

== Example playbooks

You can use few examples from https://github.com/kameshsampath/ansible-role-openshift-spices/tree/master/examples[examples]. A copy of the same has been added to $PROJECT_HOME/project/examples.

== Running the play

- Copy the needed play from $PROJECT_HOME/project/examples to `$PROJECT_HOME/playbook.yml` directory.

From the $PROJECT_HOME run:

[source,bash,subs="marcos+,+attributes]
----
./provision.sh [<playbook-file>]
----

[TIP]
====
If you maintain different plays, then you can have them in `$PROJECT_HOME/project` and then pass the file name as argument to `provision.sh` script as decribed earlier.
====

== Adding python modules

Any python module that you need to install can added to the $PROJECT_HOME/requirements.txt, this file will be processed automatically before the play runs.

== Adding extra roles and collections

Any roles/collections that need to installed can be added to the PROJECT_HOME/requirements.yml, this file will be processed automatically before the play runs.

Please check https://docs.ansible.com/ansible/latest/galaxy/user_guide.html#installing-roles-from-galaxy[Galaxy] guide for the structure of this file.

== License

https://github.com/kameshsampath/openshift-spice-runner/tree/master/LICENSE[Apache v2]

== Author Information

mailto:kamesh.sampath@hotmail.com[Kamesh Sampath]

== Issues

https://github.com/kameshsampath/openshift-spice-runner/issues[Issues]
