---
- name: OpenShift Serverless with OpenShift Pipelines
  hosts: all
  connection: local
  
  vars:
    ocp_version: 4.5.6
    download_clients: False
    deploy_serverless: True
    deploy_kafka: False
    deploy_camel_k: False
    deploy_pipelines: True
    deploy_argocd: True
    users:
      create: True
      start: 0
      end: 0
      prefix: user
    user_password: ""

  environment:
    K8S_AUTH_KUBECONFIG: "{{ kubeconfig }}"

  roles:
    - kameshsampath.openshift_app_spices
  
  